services:
    - type: web
      name: letterboxd-movie-recommendations-api
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: python -m api.main
      envVars:
          - key: PYTHON_VERSION
            value: 3.12.0
          - key: PORT
            value: 10000
